on:
  push:
    branches:
      - main

name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: wlixcc/SFTP-Deploy-Action@v1.0
      with:
        username: bcstadskanaal.htdocs.github
        server: bcstadskanaal.blob.core.windows.net
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} 
        local_path: './static/*'
        remote_path: /
        args: -o ConnectTimeout=5