on: push

name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 📂 Sync files
      id: sftp
      uses: danhendrickson/sftp-transfer-action@v1.23
      with:
        server: ${{ secrets.FTP_HOST }}
        user: ${{ secrets.FTP_USER }}
        pass: ${{ secrets.FTP_PASSWORD }}
        port: 22
        local-path: './docs/'
        remote-path: '/public_html/'

    - name: 📈 Transfer Status
      run: echo "Transfer Status - ${{ steps.sftp.outputs.transferStatus }}"
